In [1]:
#Importamos librería Numpy 
import numpy as np

# Creación y Indexación:

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las
posiciones múltiplos de 5.


In [4]:
array1 = np.random.randint(10, 100, (50))
array1

array([94, 19, 96, 76, 59, 47, 35, 94, 60, 28, 33, 35, 59, 77, 41, 34, 40,
       45, 11, 31, 30, 22, 24, 89, 22, 79, 86, 61, 37, 24, 98, 90, 86, 21,
       99, 35, 51, 40, 98, 44, 96, 32, 94, 70, 59, 70, 70, 96, 65, 90])

In [5]:
#Podemos hacerlo con np.where o directamente. La diferencia entre ambos es que np.where nos dará las posiciones de los elementos
# De la otra forma solo nos dará los elementos directamente. 

array1[(array1 % 5 == 0)]

array([35, 60, 35, 40, 45, 30, 90, 35, 40, 70, 70, 70, 65, 90])

In [6]:
posiciones_indice = np.where(array1 % 5 == 0)[0]
print(posiciones_indice)
array1[posiciones_indice]

[ 6  8 11 16 17 20 31 35 37 43 45 46 48 49]


array([35, 60, 35, 40, 45, 30, 90, 35, 40, 70, 70, 70, 65, 90])

2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para
obtener los elementos en las posiciones impares.


In [9]:
array2 = np.random.randint(1, 21, (30))
array2

array([14,  2,  6, 12,  3,  8,  1,  7, 11,  7, 12, 16, 12, 15,  8, 15, 15,
        1,  9,  4, 12, 12,  1,  7, 18, 13, 19, 20,  6,  4])

In [11]:
# Accedemos a elementos en POSICIONES IMPARES accediendo a la posición 1 que es impar y seleccionamos todo :: con saltos (steps) de dos en dos. 

array2[1::2]

array([ 2, 12,  8,  7,  7, 16, 15, 15,  1,  4, 12,  7, 13, 20,  4])


3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar
comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben
estar redondeados a 2 decimales.


In [33]:
array_2d = np.random.sample(( 4, 6)).round(2)+1  #el +1 se suma a todos los elementos del array 
array_2d

array([[1.83, 1.9 , 1.33, 1.43, 1.98, 1.8 ],
       [1.17, 1.88, 1.28, 1.99, 1.77, 1.87],
       [1.88, 1.28, 1.33, 1.86, 1.64, 1.15],
       [1.2 , 1.63, 1.61, 1.37, 1.47, 1.64]])

In [28]:
# Accedemos a la última fila de la matriz 
array_2d[-1]


array([1.2 , 1.05, 1.79, 1.36, 1.86, 1.68])

In [30]:
# Si quisiéramos acceder a la última columna haríamos
# Seleccionamos todas las filas y última columna (-1)
array_2d[:, -1]

array([1.57, 1.27, 1.1 , 1.68])


4. Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la
segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.


In [35]:
array_2d_2 = np.random.rand(6,4).round(2)
array_2d_2

array([[0.9 , 0.14, 0.51, 0.05],
       [0.3 , 0.06, 0.31, 0.55],
       [0.39, 0.8 , 0.4 , 0.34],
       [0.98, 0.6 , 0.56, 0.7 ],
       [0.94, 0.22, 0.1 , 0.2 ],
       [0.9 , 0.69, 0.52, 0.34]])

In [37]:
# Accedemos a la segunda columna de la matriz, cuya posición es 1.
# Seleccionamos todas las filas y accedemos a la segunda columna 
array_2d_2[:, 1]

array([0.14, 0.06, 0.8 , 0.6 , 0.22, 0.69])


5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores
negativos.


In [33]:
array_1d_1 = np.random.randint(-50, 50,(30))
array_1d_1

array([-22,  22,  37,  42,  46, -49,  15, -41, -25,  -9, -16, -26,  12,
       -13,  29,  10,  47,  18,  36, -45,  19, -39, -40,   9, -22,  49,
         1, -18, -16,  -8])

In [34]:
#Una forma de hacerlo mas sencilla que con np.where(): 
array_1d_1[(array_1d_1 < 0)]

array([-22, -49, -41, -25,  -9, -16, -26, -13, -45, -39, -40, -22, -18,
       -16,  -8])

In [35]:
# Método usando np.where()
posicion_negativos = np.where(array_1d_1 < 0)
array_1d_1[posicion_negativos]

array([-42, -19, -42, -28, -34, -26, -32, -28, -18, -41, -22, -23,  -1,
       -38,  -6, -43,  -7])


6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los
elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?


In [36]:
array3 = np.random.rand(10).round(2)
array3

array([0.1 , 0.98, 0.97, 0.93, 0.08, 0.33, 0.33, 0.87, 0.49, 0.47])

In [20]:
# Podemos hacer la condición de dos formas.
# primera opcion 
array3[(array3 > 0.5)]

array([0.73, 0.97, 0.55, 0.88, 0.6 ])

In [38]:
# segunda opcion con np.where 
posicion = np.where(array3 > 0.5)
#Posiciones de los elementos
print(f' Esta son las posiciones de los elementos que cumplen la condición: {posicion}') 
array3[posicion]

 Esta son las posiciones de los elementos que cumplen la condición: (array([1, 2, 3, 7], dtype=int64),)


array([0.98, 0.97, 0.93, 0.87])


7. Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que
son divisibles por 3 y por 4.


In [39]:
array4 = np.random.randint(1,101,(40))
array4

array([ 90, 100,  53,  47, 100,  54,  30,  53,  45,  28,   6,  31,  93,
        12,   1,  54,  57,  44,  22,   2,  73,  39,  93,  63,  88,  93,
        39,  39,   6,  63,  44,  82,  72,  92,  31,  89,  56,  66,  50,
        55])

In [41]:
# Especificamos dos condiciones que debe cumplir con & (and):
array4[(array4 % 3 == 0) & (array4 % 4 == 0)] 

array([12, 72])


8. BONUS: Crea un array 3D de forma (2, 3, 5) con números enteros entre 0
y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.


In [42]:
array5 = np.random.randint(0, 101,(2, 3,5))
array5
# Creamos array de 3D con forma (2,3,5)

array([[[96, 80, 64, 62, 28],
        [76, 67, 67, 74, 56],
        [43, 77, 69, 27, 66]],

       [[49, 64, 55, 64, 39],
        [73, 56, 39, 88, 80],
        [43, 28, 40, 33, 32]]])

In [43]:
# Reemplazamos los elementos multiplos de 3 
array5[(array5 % 3 == 0)] = 0 
array5

array([[[ 0, 80, 64, 62, 28],
        [76, 67, 67, 74, 56],
        [43, 77,  0,  0,  0]],

       [[49, 64, 55, 64,  0],
        [73, 56,  0, 88, 80],
        [43, 28, 40,  0, 32]]])


## Reshape y Transpose:
### Ejercicios con reshape:
1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive).
Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es
correcta para hacer este cambio.


In [19]:
array6 = np.random.randint(1, 101, (2,3,4))
array6

array([[[76, 57, 31, 58],
        [16, 51, 32, 84],
        [15, 55, 94, 82]],

       [[59, 77, 81, 32],
        [97, 38, 51, 80],
        [98, 76, 96,  8]]])

In [20]:
array_nuevo = array6.reshape(2,-1)
array_nuevo

array([[76, 57, 31, 58, 16, 51, 32, 84, 15, 55, 94, 82],
       [59, 77, 81, 32, 97, 38, 51, 80, 98, 76, 96,  8]])


2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza
reshape para convertirlo en un array 2D.


In [10]:
array7 = np.random.randint(1, 60, (3,4,5))
array7

array([[[56,  7, 18, 29,  7],
        [45, 58, 57, 25,  2],
        [45,  2, 24, 25, 14],
        [ 9,  2, 36, 32, 53]],

       [[50, 18,  1, 15, 56],
        [53, 15, 32,  9, 53],
        [41, 36, 26, 44, 22],
        [39, 27, 35, 23,  7]],

       [[45, 15,  8,  2, 12],
        [42, 42,  7, 13, 11],
        [33, 30, 24, 25, 50],
        [49,  7,  1,  7, 12]]])

In [11]:
array_reshape = array7.reshape(2, -1) # Convertimos el array con reshape() a dos dimensiones y cogemos todo, hasta el último elemento (-1). 
array_reshape

array([[56,  7, 18, 29,  7, 45, 58, 57, 25,  2, 45,  2, 24, 25, 14,  9,
         2, 36, 32, 53, 50, 18,  1, 15, 56, 53, 15, 32,  9, 53],
       [41, 36, 26, 44, 22, 39, 27, 35, 23,  7, 45, 15,  8,  2, 12, 42,
        42,  7, 13, 11, 33, 30, 24, 25, 50, 49,  7,  1,  7, 12]])


3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para
convertirlo en un array 2D.


In [2]:
array_3D = np.random.rand(4,3,2)
array_3D

array([[[0.051351  , 0.98696563],
        [0.05019352, 0.36141805],
        [0.21649832, 0.488404  ]],

       [[0.30819003, 0.01711355],
        [0.66927382, 0.97422758],
        [0.03600303, 0.95608899]],

       [[0.06603821, 0.47292867],
        [0.72169637, 0.1621065 ],
        [0.99387851, 0.64679467]],

       [[0.96826312, 0.52004953],
        [0.79933004, 0.35737151],
        [0.64409155, 0.29894428]]])

In [3]:
nuevo_array_3D = array_3D.reshape(2, -1)
nuevo_array_3D

array([[0.051351  , 0.98696563, 0.05019352, 0.36141805, 0.21649832,
        0.488404  , 0.30819003, 0.01711355, 0.66927382, 0.97422758,
        0.03600303, 0.95608899],
       [0.06603821, 0.47292867, 0.72169637, 0.1621065 , 0.99387851,
        0.64679467, 0.96826312, 0.52004953, 0.79933004, 0.35737151,
        0.64409155, 0.29894428]])


### Ejercicios con transpose:
4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y
obtener un nuevo array con forma (5, 4, 3).


In [21]:
array_reshape   


array([[56,  7, 18, 29,  7, 45, 58, 57, 25,  2, 45,  2, 24, 25, 14,  9,
         2, 36, 32, 53, 50, 18,  1, 15, 56, 53, 15, 32,  9, 53],
       [41, 36, 26, 44, 22, 39, 27, 35, 23,  7, 45, 15,  8,  2, 12, 42,
        42,  7, 13, 11, 33, 30, 24, 25, 50, 49,  7,  1,  7, 12]])

In [30]:
array_nuevo = array_reshape.reshape(5,4,3)
array_nuevo

array([[[56,  7, 18],
        [29,  7, 45],
        [58, 57, 25],
        [ 2, 45,  2]],

       [[24, 25, 14],
        [ 9,  2, 36],
        [32, 53, 50],
        [18,  1, 15]],

       [[56, 53, 15],
        [32,  9, 53],
        [41, 36, 26],
        [44, 22, 39]],

       [[27, 35, 23],
        [ 7, 45, 15],
        [ 8,  2, 12],
        [42, 42,  7]],

       [[13, 11, 33],
        [30, 24, 25],
        [50, 49,  7],
        [ 1,  7, 12]]])

In [33]:

array_transpose = np.transpose(array_nuevo,(0,1,2))
array_transpose

array([[[56,  7, 18],
        [29,  7, 45],
        [58, 57, 25],
        [ 2, 45,  2]],

       [[24, 25, 14],
        [ 9,  2, 36],
        [32, 53, 50],
        [18,  1, 15]],

       [[56, 53, 15],
        [32,  9, 53],
        [41, 36, 26],
        [44, 22, 39]],

       [[27, 35, 23],
        [ 7, 45, 15],
        [ 8,  2, 12],
        [42, 42,  7]],

       [[13, 11, 33],
        [30, 24, 25],
        [50, 49,  7],
        [ 1,  7, 12]]])


5. Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de 
los ejes y obtener un nuevo array con forma (3, 2, 4).


In [34]:
nuevo_array_3D

array([[0.051351  , 0.98696563, 0.05019352, 0.36141805, 0.21649832,
        0.488404  , 0.30819003, 0.01711355, 0.66927382, 0.97422758,
        0.03600303, 0.95608899],
       [0.06603821, 0.47292867, 0.72169637, 0.1621065 , 0.99387851,
        0.64679467, 0.96826312, 0.52004953, 0.79933004, 0.35737151,
        0.64409155, 0.29894428]])

In [36]:
nuevo_array3d = nuevo_array_3D.reshape(3,2,4)
nuevo_array3d

array([[[0.051351  , 0.98696563, 0.05019352, 0.36141805],
        [0.21649832, 0.488404  , 0.30819003, 0.01711355]],

       [[0.66927382, 0.97422758, 0.03600303, 0.95608899],
        [0.06603821, 0.47292867, 0.72169637, 0.1621065 ]],

       [[0.99387851, 0.64679467, 0.96826312, 0.52004953],
        [0.79933004, 0.35737151, 0.64409155, 0.29894428]]])

In [37]:
transpose1 = np.transpose(nuevo_array3d, (0,1,2))
transpose1

array([[[0.051351  , 0.98696563, 0.05019352, 0.36141805],
        [0.21649832, 0.488404  , 0.30819003, 0.01711355]],

       [[0.66927382, 0.97422758, 0.03600303, 0.95608899],
        [0.06603821, 0.47292867, 0.72169637, 0.1621065 ]],

       [[0.99387851, 0.64679467, 0.96826312, 0.52004953],
        [0.79933004, 0.35737151, 0.64409155, 0.29894428]]])


## Preguntas teóricas:

6. ¿Qué diferencia existe entre el reshape y el transpose?

- La función reshape se utiliza para cambiar la forma de una matriz sin cambiar los datos que contiene. 
    Permite reorganizar los elementos de una matriz en una nueva forma especificada por el usuario, siempre y cuando el número total de elementos sea el mismo que el original.

- La función transpose se utiliza para intercambiar filas y columnas de una matriz.
    Cambia la disposición de los elementos en términos de dimensiones, es decir, rota la matriz.

RESHAPE reorganiza los elementos de una matriz en una nueva forma sin cambiar su disposición, TRANSPOSE intercambia filas y columnas, cambiando la disposición de la matriz.


7. ¿Y entre el transpose y el swapaxes?

TRANSPOSE es más general y puede permutar todas las dimensiones de una matriz, usada para intercambiar filas y columnas en matrices bidimensionales.
SWAPAXES es más específico y se utiliza únicamente para intercambiar dos ejes específicos. La elección entre una u otra depende de los requisitos específicos de manipulación de dimensiones en su aplicación.


## Funciones Aritméticas y Estadísticas:
1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo
tengan 1 decimal.


In [5]:
array_7 = np.random.rand(2,3,5).round(1)
array_7

array([[[0.5, 0.3, 0.5, 0.7, 0.5],
        [0.2, 0.7, 0.4, 0.7, 0.7],
        [0.6, 1. , 0.4, 0.1, 0.8]],

       [[0.1, 0.8, 0.2, 0.2, 0.5],
        [0.4, 0.8, 0.3, 0.9, 0.8],
        [0.4, 0.9, 0.3, 0.1, 0.5]]])


2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero
basándonos en los valores del primer array bajo las siguientes condiciones:
Si el valor del array es igual que la media, se reemplaza por "A".
Si el valor del array es mayor que la media, se reemplaza por "B".
Si el valor del array es menor que la media, se reemplaza por "C".
Si el valor es igual que el máximo, se reemplaza por "D".
Si el valor es igual que el mínimo, se reemplaza por "E"

In [7]:
array_vacio = np.empty((2,3,5))
array_vacio

array([[[0.5, 0.3, 0.5, 0.7, 0.5],
        [0.2, 0.7, 0.4, 0.7, 0.7],
        [0.6, 1. , 0.4, 0.1, 0.8]],

       [[0.1, 0.8, 0.2, 0.2, 0.5],
        [0.4, 0.8, 0.3, 0.9, 0.8],
        [0.4, 0.9, 0.3, 0.1, 0.5]]])