In [1]:
import numpy as np

# Creación y Indexación:

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las
posiciones múltiplos de 5.


In [3]:
array = np.random.randint(10, 100, (50))
array

array([10, 39, 44, 64, 53, 98, 60, 69, 16, 39, 84, 38, 53, 44, 41, 55, 62,
       34, 14, 50, 58, 80, 60, 75, 66, 96, 19, 44, 24, 22, 52, 69, 19, 38,
       18, 32, 56, 52, 79, 83, 83, 49, 56, 38, 34, 18, 46, 82, 74, 28])

In [14]:
posiciones_indice = np.where(array % 5 == 0)[0]
print(posiciones_indice)
array[posiciones_indice]

[ 0  6 15 19 21 22 23]


array([10, 60, 55, 50, 80, 60, 75])

2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para
obtener los elementos en las posiciones impares.


In [17]:
arra2 = np.random.randint(1, 21, (30))
arra2

array([18, 20,  2,  3, 17, 18,  2,  2, 11,  2,  1, 11, 17,  4, 20,  6, 11,
        8, 14,  9, 15, 19, 11, 12,  3,  8,  3,  6,  7, 12])

In [23]:
# Acceder a elementos impares 
arra2[1::2]

array([20,  3, 18,  2,  2, 11,  4,  6,  8,  9, 19, 12,  8,  6, 12])


3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar
comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben
estar redondeados a 2 decimales.


In [52]:
array_2d = np.random.sample((4, 6)).round(2)+1  #el +1 se suma a todos los elementos del array 
array_2d

array([[1.83, 1.43, 1.05, 1.28, 1.73, 1.61],
       [1.24, 1.71, 1.66, 1.93, 1.15, 1.72],
       [1.38, 1.81, 1.92, 1.65, 1.45, 1.87],
       [1.7 , 1.2 , 1.61, 1.21, 1.26, 1.  ]])


4. Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la
segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.


In [53]:
array_dos = np.random.rand(6,4).round(2)
array_dos

array([[0.03, 0.23, 0.63, 0.59],
       [0.83, 0.54, 0.43, 0.23],
       [0.91, 0.41, 0.26, 0.95],
       [0.85, 0.46, 0.85, 0.85],
       [0.86, 0.92, 0.65, 0.94],
       [0.47, 0.57, 0.16, 0.9 ]])

In [54]:
array_dos[1]

array([0.83, 0.54, 0.43, 0.23])


5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores
negativos.


In [56]:
array_1D = np.random.randint(-50, 50,(30))
array_1D

array([  9,  21, -20, -36,   6,  29,  18,   2, -30, -15, -30,  -1,  17,
       -26,  43,   8,  -7,  22, -12, -18, -43, -23, -32,  27, -27,  33,
        15,  15, -45, -46])

In [59]:
posciion_negativos = np.where(array_1D < 0)
array_1D[posciion_negativos]

array([-20, -36, -30, -15, -30,  -1, -26,  -7, -12, -18, -43, -23, -32,
       -27, -45, -46])


6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los
elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?


In [60]:
array3 = np.random.rand(10).round(2)
array3

array([0.07, 0.47, 0.15, 0.67, 0.35, 0.75, 0.86, 0.98, 0.65, 0.95])

In [72]:
# Podemos hacer la condición de dos formas.
# primera opcion 
array3[(array3 > 0.5)]

array([0.67, 0.75, 0.86, 0.98, 0.65, 0.95])

In [62]:
# segunda opcion con np.where 
posicion = np.where(array3 > 0.5)
print(posicion) #Posiciones de los elementos
array3[posicion]

(array([3, 5, 6, 7, 8, 9], dtype=int64),)


array([0.67, 0.75, 0.86, 0.98, 0.65, 0.95])


7. Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que
son divisibles por 3 y por 4.


In [63]:
array_4 = np.random.randint(1,101,(40))
array_4

array([20, 53,  1, 80, 27, 61, 29, 99, 51, 97, 80, 61, 59, 48, 10, 58, 40,
       55, 53, 29, 32, 93, 89, 40, 49, 37, 28, 71, 43, 87, 13, 59, 29, 35,
       93, 61, 37, 10, 13, 47])

In [71]:
array_4[(array_4 % 3 == 0) & (array_4 % 4 == 0)] 

array([48])


8. BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0
y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.


In [85]:
array_5 = np.random.randint(0, 101, (2,3,5))
array_5 

TypeError: Cannot interpret '50' as a data type


## Reshape y Transpose:
### Ejercicios con reshape:
1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive).
Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es
correcta para hacer este cambio.



2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza
reshape para convertirlo en un array 2D.



3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para
convertirlo en un array 2D.



### Ejercicios con transpose:
4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y
obtener un nuevo array con forma (5, 4, 3).



5. Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de 
los ejes y obtener un nuevo array con forma (3, 2, 4).



## Preguntas teóricas:

6. ¿Qué diferencia existe entre el reshape y el transpose?



7. ¿Y entre el transpose y el swapaxes?



## Funciones Aritméticas y Estadísticas:
1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo
tengan 1 decimal.



2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero
basándonos en los valores del primer array bajo las siguientes condiciones:
Si el valor del array es igual que la media, se reemplaza por "A".
Si el valor del array es mayor que la media, se reemplaza por "B".
Si el valor del array es menor que la media, se reemplaza por "C".
Si el valor es igual que el máximo, se reemplaza por "D".
Si el valor es igual que el mínimo, se reemplaza por "E"